import { useParams } from "react-router-dom";
import { WebSectionShell } from "../components/WebSectionShell";

export { WebNotificationsPage } from "./WebNotificationsPage";
export function WebSupportPage() { return <WebSectionShell eyebrow="CUSTOMER CENTER" title="고객센터" description="자주 묻는 질문을 찾거나 필요한 도움을 요청합니다." sections={[{ title: "자주 묻는 질문", description: "배송·주문·환불·회원 관련 질문을 빠르게 찾습니다." }, { title: "공지사항", description: "서비스 운영과 정책 변경 소식을 확인합니다." }, { title: "1:1 문의", description: "해결되지 않은 문제를 고객센터에 문의합니다." }]} primary={{ label: "1:1 문의하기", to: "/web/support/inquiry" }} secondary={{ label: "FAQ 보기", to: "/web/support/faq" }} />; }
export { WebInquiryWritePage as WebSupportInquiryPage } from "./WebInquiryWritePage";
export function WebNoticeListPage() { return <WebSectionShell eyebrow="NOTICE" title="공지사항" description="Kopang의 새로운 소식과 정책 안내를 확인합니다." sections={[{ title: "중요 공지", description: "서비스 이용에 중요한 공지를 상단에 표시합니다." }, { title: "전체 공지", description: "공지 제목과 등록일을 목록으로 표시합니다." }]} primary={{ label: "고객센터", to: "/web/support" }} />; }
export function WebNoticeDetailPage() { const { id } = useParams(); return <WebSectionShell eyebrow="NOTICE" title={`공지사항 #${id ?? ""}`} description="공지 제목과 본문, 첨부 내용을 확인합니다." sections={[{ title: "공지 내용", description: "선택한 공지의 실제 본문이 표시될 영역입니다." }, { title: "이전·다음 글", description: "목록으로 돌아가지 않고 인접 공지를 탐색합니다." }]} primary={{ label: "목록으로", to: "/web/support/notices" }} />; }
export function WebFaqPage() { return <WebSectionShell eyebrow="FAQ" title="자주 묻는 질문" description="궁금한 내용을 검색하고 카테고리별 답변을 확인합니다." sections={[{ title: "FAQ 검색", description: "질문의 키워드를 입력해 관련 답변을 찾습니다." }, { title: "카테고리", description: "주문·배송·취소·회원 질문을 구분합니다." }, { title: "질문과 답변", description: "accordion 방식으로 답변을 펼쳐봅니다." }]} primary={{ label: "1:1 문의하기", to: "/web/support/inquiry" }} />; }
export function WebQnaListPage() { return <WebSectionShell eyebrow="Q&A" title="상품 문의" description="상품별 질문과 답변 상태를 확인합니다." sections={[{ title: "문의 검색", description: "상품명이나 문의 제목으로 목록을 찾습니다." }, { title: "문의 목록", description: "답변 대기·답변 완료 상태를 구분해 표시합니다." }]} primary={{ label: "문의 작성", to: "/web/qna/write" }} />; }
export function WebQnaDetailPage() { const { id } = useParams(); return <WebSectionShell eyebrow="Q&A" title={`상품 문의 #${id ?? ""}`} description="등록한 질문과 판매자 또는 관리자의 답변을 확인합니다." sections={[{ title: "질문", description: "문의 상품, 제목과 상세 내용이 표시됩니다." }, { title: "답변", description: "답변 상태와 답변 내용이 표시됩니다." }]} primary={{ label: "문의 목록", to: "/web/qna" }} />; }
export { WebInquiryWritePage as WebQnaWritePage } from "./WebInquiryWritePage";
