import { useParams } from "react-router-dom";
import { WebSectionShell } from "../components/WebSectionShell";

export function WebNotificationsPage() { return <WebSectionShell eyebrow="NOTIFICATIONS" title="알림" description="주문·배송·혜택 소식을 유형별로 확인합니다." sections={[{ title: "전체 알림", description: "읽지 않은 알림과 최근 알림을 시간순으로 표시합니다." }, { title: "알림 필터", description: "주문·혜택·서비스 알림을 구분해 확인합니다." }]} primary={{ label: "쇼핑홈으로", to: "/web" }} />; }
export function WebSupportPage() { return <WebSectionShell eyebrow="CUSTOMER CENTER" title="고객센터" description="자주 묻는 질문을 찾거나 필요한 도움을 요청합니다." sections={[{ title: "자주 묻는 질문", description: "배송·주문·환불·회원 관련 질문을 빠르게 찾습니다." }, { title: "공지사항", description: "서비스 운영과 정책 변경 소식을 확인합니다." }, { title: "1:1 문의", description: "해결되지 않은 문제를 고객센터에 문의합니다." }]} primary={{ label: "1:1 문의하기", to: "/web/support/inquiry" }} secondary={{ label: "FAQ 보기", to: "/web/support/faq" }} />; }
export function WebSupportInquiryPage() { return <WebSectionShell eyebrow="CUSTOMER CENTER" title="1:1 문의" description="문의 유형과 주문을 선택하고 상세 내용을 작성합니다." sections={[{ title: "문의 유형", description: "주문·배송·환불·회원 중 문의 분야를 선택합니다." }, { title: "문의 내용", description: "제목, 상세 설명과 첨부 이미지를 입력합니다." }]} primary={{ label: "문의 등록", to: "/web/my/inquiries" }} secondary={{ label: "고객센터", to: "/web/support" }} />; }
export function WebNoticeListPage() { return <WebSectionShell eyebrow="NOTICE" title="공지사항" description="Kopang의 새로운 소식과 정책 안내를 확인합니다." sections={[{ title: "중요 공지", description: "서비스 이용에 중요한 공지를 상단에 표시합니다." }, { title: "전체 공지", description: "공지 제목과 등록일을 목록으로 표시합니다." }]} primary={{ label: "고객센터", to: "/web/support" }} />; }
export function WebNoticeDetailPage() { const { id } = useParams(); return <WebSectionShell eyebrow="NOTICE" title={`공지사항 #${id ?? ""}`} description="공지 제목과 본문, 첨부 내용을 확인합니다." sections={[{ title: "공지 내용", description: "선택한 공지의 실제 본문이 표시될 영역입니다." }, { title: "이전·다음 글", description: "목록으로 돌아가지 않고 인접 공지를 탐색합니다." }]} primary={{ label: "목록으로", to: "/web/support/notices" }} />; }
export function WebFaqPage() { return <WebSectionShell eyebrow="FAQ" title="자주 묻는 질문" description="궁금한 내용을 검색하고 카테고리별 답변을 확인합니다." sections={[{ title: "FAQ 검색", description: "질문의 키워드를 입력해 관련 답변을 찾습니다." }, { title: "카테고리", description: "주문·배송·취소·회원 질문을 구분합니다." }, { title: "질문과 답변", description: "accordion 방식으로 답변을 펼쳐봅니다." }]} primary={{ label: "1:1 문의하기", to: "/web/support/inquiry" }} />; }
export function WebQnaListPage() { return <WebSectionShell eyebrow="Q&A" title="상품 문의" description="상품별 질문과 답변 상태를 확인합니다." sections={[{ title: "문의 검색", description: "상품명이나 문의 제목으로 목록을 찾습니다." }, { title: "문의 목록", description: "답변 대기·답변 완료 상태를 구분해 표시합니다." }]} primary={{ label: "문의 작성", to: "/web/qna/write" }} />; }
export function WebQnaDetailPage() { const { id } = useParams(); return <WebSectionShell eyebrow="Q&A" title={`상품 문의 #${id ?? ""}`} description="등록한 질문과 판매자 또는 관리자의 답변을 확인합니다." sections={[{ title: "질문", description: "문의 상품, 제목과 상세 내용이 표시됩니다." }, { title: "답변", description: "답변 상태와 답변 내용이 표시됩니다." }]} primary={{ label: "문의 목록", to: "/web/qna" }} />; }
export function WebQnaWritePage() { return <WebSectionShell eyebrow="Q&A" title="상품 문의 작성" description="문의할 상품과 질문 유형을 선택해 내용을 작성합니다." sections={[{ title: "문의 상품", description: "상품 상세에서 넘어온 상품 정보를 확인합니다." }, { title: "문의 내용", description: "공개 여부, 제목과 상세 질문을 입력합니다." }]} primary={{ label: "문의 등록", to: "/web/qna" }} />; }
